name: Mirror repositories
on:
  workflow_dispatch:
  schedule:
    - cron: '11 1/6 * * *'
concurrency:
  group: ${{ github.workflow }}
jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: elpa
            url: git://git.savannah.gnu.org/emacs/elpa.git
            mirror: false
          - name: nongnu
            url: git://git.savannah.gnu.org/emacs/nongnu.git
            mirror: false
          - name: org-mode
            url: git://git.savannah.gnu.org/emacs/org-mode.git
            mirror: true

    steps:
      - name: Configure
        id: config
        run: |
          if [[ ${{ matrix.mirror }} = true ]]; then
            echo >> "$GITHUB_OUTPUT" working_dir=${{ matrix.name }}.git
            echo >> "$GITHUB_OUTPUT" flag=--mirror
          else
            echo >> "$GITHUB_OUTPUT" working_dir=${{ matrix.name }}
            echo >> "$GITHUB_OUTPUT" flag=
          fi

      - name: Clone
        run: |
          git clone ${{ steps.config.outputs.flag }} ${{ matrix.url }}

      - name: Push
        working-directory: ${{ steps.config.outputs.working_dir }}
        run: |
          git remote set-url --push origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/${{ matrix.name }}.git
          git push --force origin --all
