name: Mirror repositories
on:
  workflow_dispatch:
  schedule:
    - cron: '11 1/6 * * *'
concurrency:
  group: ${{ github.workflow }}
jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repository:
          - elpa
          - nongnu
          - org-mode
    steps:
      - name: Clone
        run: |
          git clone https://git.savannah.gnu.org/git/emacs/${{ matrix.repository }}.git
      - name: Push
        working-directory: ${{ matrix.repository }}
        run: |
          git remote set-url --push origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/${{ matrix.repository }}.git
          git push --force origin HEAD
